title: UBC Sports Data Science
description: UBC student ran data science club

# Set the theme to minima
remote_theme: jekyll/minima

# Optional: Add any other custom settings or configuration you may want
